name: CI

on:
  
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew 
          ./gradlew build 
          ls -ltr

      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew 
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }} 

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copia de Jar a Raiz de proyecto
        run: |
          ls
          cp $GITHUB_WORKSPACE/build/libs/testing-web-2.6.0.jar .
          chmod 777 testing-web-2.6.0.jar
          ls -lt
      - name: Docker Build
        run: | 
          docker build --tag ivanpizarroq/microservicio-java:latest .
          docker images

      - name: Docker Push
        run: |
          docker push ivanpizarroq/microservicio-java 

  deploy: 
    runs-on: self-hosted 
    needs: build
    steps: 

    - uses: actions/checkout@v3
    - name: Set PowerShell Execution Policy
      run: |
        Set-ExecutionPolicy Unrestricted
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yml




     
